---
title: "Final Project 1"
author: "Avery Holloman"
date: "2023-09-23"
output:
  html_document:
    toc: true
    toc_float: true
  pdf_document: default
  output:
  html_document:
    code_folding: hide
    output:
  html_notebook: default
  github_document: default
---

```{r}
setwd("C:/Users/aholl/Desktop/Data Science Portfolio/Project #1/project#1newdata/Colorado EPA Data")
```

```{r}
# Load packages
library(tidyverse)
library(readxl)
library(lubridate)
library(ggplot2)
library(ggthemes)
library(ggpubr)
library(cowplot)
library(ggcorrplot)
library(corrplot)
library(caret)

library(rpart)
library(rpart.plot)
library(randomForest)
library(ranger)
library(e1071)
library(class)
library(kknn)
library(kernlab)
library(nnet)
library(neuralnet)
library(ROCR)
library(pROC)
```

```{r chunk_name, message=FALSE, warning=FALSE}
library(readxl)
Book1 <- read_excel("Book1.xlsx")
```

```{r setup, include = FALSE}
library(ggplot2)
library(dplyr)
knitr::opts_chunk$set(fig.width = 5, fig.asp = 1/3)
```


```{r}
# Drop "CHEMICAL REPORT ID" column from data frame Book1 and save it as Book2
Book2 <- Book1[, -c(3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27)]
View(Book2)
```

```{r}
# Drop "CHEMICAL REPORT ID" column from data frame Book1 and save it as Book2
BookData <- Book1[, -c(1,3,4,5,6,27,28,28,30,31,32)]
View(BookData)
```

```{r}
BookData %>% select(-`DOMESTIC PC ADDRESS LINE2`,`DOMESTIC PC CITY`, `DOMESTIC PC COUNTY / PARISH`,`DOMESTIC PC COUNTY / PARISH`,`DOMESTIC PC STATE`,`DOMESTIC PC POSTAL CODE`, `DOMESTIC PC DUN & BRADSTREET NUMBER`,`FOREIGN PARENT COMPANY NAME`, `FOREIGN PC ADDRESS LINE1`,`SITE ADDRESS LINE2`,`SITE CITY`, `SITE COUNTY / PARISH`, `SITE LATITUDE`,`EPA FACILITY REGISTRY ID`,`WORKERS CODE`,WORKERS,`C / C PROD CAT CODE`,`COMM WORKERS CODE`)
view(BookData)
```



```{r}
list_names <- colnames(BookData)[colnames(BookData$`CHEMICAL NAME`)
```

```{r}
list_transpose(BookData$`CHEMICAL NAME`)
```

```{r}
#remove duplicates in R dataframe
Book1 <- Book1[!duplicated(Book1),]
Book1 

```
  
```{r}
tibble::lst(Book1$`CHEMICAL NAME`)

```

```{r}
table(Book1$`CHEMICAL NAME`, useNA = 'always')

````

```{r}
install.packages("gptstudio")
```

```{r}
install.packages("pak")
```
```{r}
install.packages("usethis")
```


```{r}
pak::pak("r-lib/usethis")
```

```{r}
Sys.getenv("OPENAI_API_KEY")
```
