---
title: "Project 1"
author: "Avery Holloman"
date: "2023-09-25"
output: html_document
---
```{r}
setwd("C:/Users/aholl/Desktop/Data Science Portfolio/Project #1/project#1data")
```

```{r}
library(readxl)
Summary_Table_by_Contaminant <- read_excel("C:/Users/aholl/Desktop/Data Science Portfolio/Project #1/project#1newdata/Summary Table by Contaminant.xlsx", 
    col_types = c("text", "numeric", "numeric", 
        "numeric", "numeric", "numeric", 
        "numeric", "text", "text"))
View(Summary_Table_by_Contaminant)
```

```{r}
library(dplyr)
```

```{r}
water_data <- Summary_Table_by_Contaminant
```

```{r}
# Remove any duplicate rows
water_data <- distinct(water_data)
```


```{r}
# Load the required libraries
library(dplyr)
library(ggplot2)
```

```{r}
#Summary statistics
Summary_Table_by_Contaminant(water_data)
```


```{r}
#  Standardize the data by subtracting the mean and dividing by the standard deviation
water_data <- scale(water_data)
```

```{r}
#  Standardize the data by subtracting the mean and dividing by the standard deviation
water_data <- scale(water_data)
```

```{r}
# Compute the covariance matrix of the standardized data
cov_matrix <- cov(water_data)
```

```{r}
# Compute the eigenvalues and eigenvectors of the covariance matrix
eigen_values <- eigen(cov_matrix)$values
eigen_vectors <- eigen(cov_matrix)$vectors
```

```{r}
# Compute the proportion of variance explained by each principal component
variance_explained <- eigen_values / sum(eigen_values)
```

```{r}
# Compute the cumulative proportion of variance explained by the first k principal components
cumulative_variance_explained <- cumsum(variance_explained)
```

```{r}
# Plot the cumulative proportion of variance explained by the first k principal components
plot(cumulative_variance_explained, xlab = "Number of Principal Components", ylab = "Cumulative Proportion of Variance Explained", type = "b")
```

```{r}
# Compute the principal component scores
principal_component_scores <- water_data %*% eigen_vectors
```

```{r}
# Plot the first two principal component scores
plot(principal_component_scores[, 1], principal_component_scores[, 2], xlab = "First Principal Component", ylab = "Second Principal Component")
```

```{r}
# Plot the first two principal component scores, colored by the target variable
plot(principal_component_scores[, 1], principal_component_scores[, 2], col = water_data$`Contaminant Name`, xlab = "First Principal Component", ylab = "Second Principal Component")
```

```{r}
# Plot the first two principal component scores, colored by the target variable, with a legend
plot(principal_component_scores[, 1], principal_component_scores[, 2], col = water_data$`Contaminant Name`, xlab = "First Principal Component", ylab = "Second Principal Component")
legend("bottomright", legend = levels(water_data$`Contaminant Name`), col = 1:3, pch = 1)
```

